/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */
import type { BaseAnalyticData } from "./baseAnalyticData";

export interface AnalyticDataResponse {
  readonly bought: BaseAnalyticData;
  readonly increasedPercentage: string;
  readonly sold: BaseAnalyticData;
}
