/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */

export type BaseMemeResponseStatus =
  (typeof BaseMemeResponseStatus)[keyof typeof BaseMemeResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BaseMemeResponseStatus = {
  active: "active",
  hidden: "hidden",
  completed: "completed",
} as const;
