/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */
import type { BaseTransactionResponseType } from "./baseTransactionResponseType";

export interface BaseTransactionResponse {
  readonly amountNative: string;
  readonly amountToken: string;
  readonly created_at: string;
  readonly createdTime: number;
  readonly creator: string;
  readonly id: number;
  readonly tokenAddress: string;
  readonly tx: string;
  readonly type: BaseTransactionResponseType;
  readonly updated_at: string;
  readonly virtualNativeReserve: string;
  readonly virtualTokenReserve: string;
  readonly volume: string;
}
