/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * EVM TAX FARM API
 * OpenAPI spec version: 1.0.0
 */

export interface CommentResponse {
  readonly content: string;
  readonly created_at: string;
  readonly id: number;
  readonly image: string;
  readonly owner: string;
  readonly status: string;
  readonly taxFarmHash: string;
  readonly updated_at: string;
}
