/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */
import type { CommentResponse } from "./commentResponse";

export interface CommentPaginationResponse {
  readonly data: readonly CommentResponse[];
  readonly page: number;
  readonly pageSize: number;
  readonly total: number;
}
