/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */

export interface CreateMemeOffChainDto {
  description?: string;
  discord?: string;
  image?: string;
  telegram?: string;
  tokenAddress: string;
  website?: string;
  x?: string;
}
