/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */
import type { CreateAllocationDto } from "./createAllocationDto";

export interface CreateManyAllocationsDto {
  allocations: CreateAllocationDto[];
  tokenAddress: string;
}
