/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */

export interface CreateMemeOffChainResponse {
  readonly createdTime: number;
  readonly createdTx: string;
  readonly creator: string;
  readonly discord: string;
  readonly telegram: string;
  readonly website: string;
  readonly x: string;
}
