/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */

export type MemeResponseStatus =
  (typeof MemeResponseStatus)[keyof typeof MemeResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemeResponseStatus = {
  active: "active",
  hidden: "hidden",
  completed: "completed",
} as const;
