/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * EVM TAX FARM API
 * OpenAPI spec version: 1.0.0
 */

export interface MockCreateTaxFarmDto {
  banner: string;
  createTime: number;
  creator: string;
  decimals: string;
  description: string;
  feeTier: number;
  logo: string;
  marketCap: number;
  revenue: number;
  symbol: string;
  telegram: string;
  tokenAddress: string;
  tokenName: string;
  totalSupply: string;
  uniswapPair: string;
  volume5m: number;
  website: string;
  X: string;
}
