/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */

export interface OHLCItem {
  readonly c: string;
  readonly h: string;
  readonly l: string;
  readonly o: string;
  readonly time: number;
}
