/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * EVM TAX FARM API
 * OpenAPI spec version: 1.0.0
 */
import type { TaxFarmResponse } from "./taxFarmResponse";

export interface TaxFarmManyResponse {
  readonly count: number;
  readonly data: TaxFarmResponse;
  readonly page: number;
  readonly pageCount: number;
  readonly total: number;
}
