/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * EVM TAX FARM API
 * OpenAPI spec version: 1.0.0
 */

export type TaxFarmControllerGetParams = {
  search?: string;
  filter?: string;
  sortBy?: string;
  order?: string;
  walletAddress?: string;
};
