/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * EVM TAX FARM API
 * OpenAPI spec version: 1.0.0
 */

export interface TaxFarmStatisticResponse {
  readonly totalRevenue: number;
  readonly totalToken: number;
  readonly totalUser: number;
}
