/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * EVM TAX FARM API
 * OpenAPI spec version: 1.0.0
 */

export type TaxFarmControllerFindAllParams = {
  search: string;
  groupBy: string;
  sortBy: string;
  order: string;
};
