/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * EVM TAX FARM API
 * OpenAPI spec version: 1.0.0
 */
import type { TaxFarmResponse } from "./taxFarmResponse";

export interface TaxFarmStatisticUserResponse {
  readonly bestToken: TaxFarmResponse;
  readonly totalRevenue: number;
  readonly totalToken: number;
}
