/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */

export type TransactionHighLightResponseType =
  (typeof TransactionHighLightResponseType)[keyof typeof TransactionHighLightResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionHighLightResponseType = {
  MemeCreated: "MemeCreated",
  Buy: "Buy",
  Sell: "Sell",
  List: "List",
} as const;
