/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */

export type TransactionControllerQueryAnalyticDuration =
  (typeof TransactionControllerQueryAnalyticDuration)[keyof typeof TransactionControllerQueryAnalyticDuration];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionControllerQueryAnalyticDuration = {
  NUMBER_3600: "3600",
  NUMBER_21600: "21600",
  NUMBER_86400: "86400",
} as const;
