/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * EVM TAX FARM API
 * OpenAPI spec version: 1.0.0
 */

export interface UpsertTaxFarmOffChainDto {
  banner?: string;
  description?: string;
  logo?: string;
  telegram?: string;
  tokenAddress: string;
  txWithdraw?: string;
  website?: string;
  X?: string;
}
