/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * A8 Pump Fun API
 * OpenAPI spec version: 0.0.12
 */

export interface UserResponse {
  readonly bio: string;
  readonly created_at: string;
  readonly id: number;
  readonly image: string;
  readonly name: string;
  readonly updated_at: string;
  readonly walletAddress: string;
}
