export const MemeAbi = [
  {
    type: "function",
    name: "BASIS_POINTS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_TOKENS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "UNIV3_FACTORY",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IUniswapV3Factory" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "agniMintCallback",
    inputs: [
      { name: "amount0Owed", type: "uint256", internalType: "uint256" },
      { name: "amount1Owed", type: "uint256", internalType: "uint256" },
      { name: "", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "factory",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IMemeFactory" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialBuy",
    inputs: [{ name: "recipient", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_token", type: "address", internalType: "address" },
      { name: "_native", type: "address", internalType: "address" },
      { name: "_univ3Factory", type: "address", internalType: "address" },
      { name: "_uniswapPair", type: "address", internalType: "address" },
      { name: "_saleAmount", type: "uint256", internalType: "uint256" },
      { name: "_tokenOffset", type: "uint256", internalType: "uint256" },
      { name: "_nativeOffset", type: "uint256", internalType: "uint256" },
      {
        name: "_listingSqrtPriceX96",
        type: "uint160",
        internalType: "uint160",
      },
      { name: "_listingFeeTier", type: "uint24", internalType: "uint24" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "listingFeeTier",
    inputs: [],
    outputs: [{ name: "", type: "uint24", internalType: "uint24" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "listingSqrtPriceX96",
    inputs: [],
    outputs: [{ name: "", type: "uint160", internalType: "uint160" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "native",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IWETH" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nativeOffset",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quoteAmountIn",
    inputs: [
      { name: "amountOut", type: "uint256", internalType: "uint256" },
      { name: "isBuyToken", type: "bool", internalType: "bool" },
    ],
    outputs: [
      { name: "actualAmountOut", type: "uint256", internalType: "uint256" },
      { name: "amountIn", type: "uint256", internalType: "uint256" },
      { name: "nativeFee", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quoteAmountOut",
    inputs: [
      { name: "amountIn", type: "uint256", internalType: "uint256" },
      { name: "isBuyToken", type: "bool", internalType: "bool" },
    ],
    outputs: [
      { name: "actualAmountIn", type: "uint256", internalType: "uint256" },
      { name: "amountOut", type: "uint256", internalType: "uint256" },
      { name: "nativeFee", type: "uint256", internalType: "uint256" },
      { name: "refund", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "reserveNative",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reserveToken",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "saleAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "swapExactIn",
    inputs: [
      { name: "amountIn", type: "uint256", internalType: "uint256" },
      { name: "minimumReceive", type: "uint256", internalType: "uint256" },
      { name: "isBuyToken", type: "bool", internalType: "bool" },
      { name: "recipient", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "swapExactOut",
    inputs: [
      { name: "amountOut", type: "uint256", internalType: "uint256" },
      { name: "maximumPay", type: "uint256", internalType: "uint256" },
      { name: "isBuyToken", type: "bool", internalType: "bool" },
      { name: "recipient", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract MemeToken" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenOffset",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "uniswapPair",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Buy",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "trader",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amountToken",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amountNative",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reserveToken",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reserveNative",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "factory",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      { name: "version", type: "uint8", indexed: false, internalType: "uint8" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "List",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "tokenLiquidity",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reserveLiquidity",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "pair",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "factory",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Sell",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "trader",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amountToken",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amountNative",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reserveToken",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reserveNative",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "factory",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
] as const;
