export const MemeFactoryAbi = [
  {
    type: "function",
    name: "createMeme",
    inputs: [
      {
        name: "params",
        type: "tuple",
        internalType: "struct IMemeFactory.MemeCreationParams",
        components: [
          { name: "name", type: "string", internalType: "string" },
          { name: "symbol", type: "string", internalType: "string" },
          { name: "tokenId", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "meme", type: "address", internalType: "address" },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "createMemeWithoutLaunching",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_symbol", type: "string", internalType: "string" },
      { name: "_tokenId", type: "uint256", internalType: "uint256" },
      { name: "_totalSupply", type: "uint256", internalType: "uint256" },
      { name: "_supplyRecipient", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "token", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "creationFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeTo",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "forLaunching",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMemeAddress",
    inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPumpContractAddress",
    inputs: [
      { name: "tokenAddress", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      {
        name: "params",
        type: "tuple",
        internalType: "struct IMemeFactory.InitializationParams",
        components: [
          {
            name: "memeImplementation",
            type: "address",
            internalType: "address",
          },
          {
            name: "uniswapV3Factory",
            type: "address",
            internalType: "address",
          },
          { name: "native", type: "address", internalType: "address" },
          { name: "feeTo", type: "address", internalType: "address" },
          { name: "tradingFeeRate", type: "uint256", internalType: "uint256" },
          { name: "listingFeeRate", type: "uint256", internalType: "uint256" },
          { name: "creationFee", type: "uint256", internalType: "uint256" },
          { name: "tokenOffset", type: "uint256", internalType: "uint256" },
          { name: "nativeOffset", type: "uint256", internalType: "uint256" },
          { name: "totalSupply", type: "uint256", internalType: "uint256" },
          { name: "saleAmount", type: "uint256", internalType: "uint256" },
          {
            name: "token0ListingSqrtPriceX96",
            type: "uint160",
            internalType: "uint160",
          },
          {
            name: "token1ListingSqrtPriceX96",
            type: "uint160",
            internalType: "uint160",
          },
          { name: "listingFeeTier", type: "uint24", internalType: "uint24" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initializeWithoutLaunching",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "listingFeeRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "listingFeeTier",
    inputs: [],
    outputs: [{ name: "", type: "uint24", internalType: "uint24" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "memeBeacon",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract UpgradeableBeacon" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "native",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nativeOffset",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proxiableUUID",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "saleAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setCreationFee",
    inputs: [
      { name: "_creationFee", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCurveConfiguration",
    inputs: [
      { name: "_totalSupply", type: "uint256", internalType: "uint256" },
      { name: "_saleAmount", type: "uint256", internalType: "uint256" },
      { name: "_tokenOffset", type: "uint256", internalType: "uint256" },
      { name: "_nativeOffset", type: "uint256", internalType: "uint256" },
      {
        name: "_token0ListingSqrtPriceX96",
        type: "uint160",
        internalType: "uint160",
      },
      {
        name: "_token1ListingSqrtPriceX96",
        type: "uint160",
        internalType: "uint160",
      },
      { name: "_listingFeeTier", type: "uint24", internalType: "uint24" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFeeTo",
    inputs: [{ name: "_feeTo", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setForLaunching",
    inputs: [{ name: "_forLaunching", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setListingFeeRate",
    inputs: [
      { name: "_listingFeeRate", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMemeImplementation",
    inputs: [
      { name: "_implementation", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setNative",
    inputs: [{ name: "_native", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTradingFeeRate",
    inputs: [
      { name: "_tradingFeeRate", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUniV3Factory",
    inputs: [
      { name: "_univ3Factory", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "token0ListingSqrtPriceX96",
    inputs: [],
    outputs: [{ name: "", type: "uint160", internalType: "uint160" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token1ListingSqrtPriceX96",
    inputs: [],
    outputs: [{ name: "", type: "uint160", internalType: "uint160" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenOffset",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tradingFeeRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "uniswapV3Factory",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "upgradeTo",
    inputs: [
      { name: "newImplementation", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "upgradeToAndCall",
    inputs: [
      { name: "newImplementation", type: "address", internalType: "address" },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "event",
    name: "AdminChanged",
    inputs: [
      {
        name: "previousAdmin",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "newAdmin",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BeaconUpgraded",
    inputs: [
      {
        name: "beacon",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ConfigurationSet",
    inputs: [
      {
        name: "native",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "uniswapV3Factory",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "feeTo",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "tradingFeeRate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "listingFeeRate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "creationFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "forLaunching",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "factory",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CurveSet",
    inputs: [
      {
        name: "totalSupply",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "saleAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tokenOffset",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "nativeOffset",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "token0ListingSqrtPriceX96",
        type: "uint160",
        indexed: false,
        internalType: "uint160",
      },
      {
        name: "token1ListingSqrtPriceX96",
        type: "uint160",
        indexed: false,
        internalType: "uint160",
      },
      {
        name: "listingFeeTier",
        type: "uint24",
        indexed: false,
        internalType: "uint24",
      },
      {
        name: "factory",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      { name: "version", type: "uint8", indexed: false, internalType: "uint8" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MemeCreated",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "meme",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "creator",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "totalSupply",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "saleAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tokenOffset",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "nativeOffset",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "factory",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MemeCreatedWithoutLaunching",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "factory",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MemeImplementationSet",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      {
        name: "factory",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Upgraded",
    inputs: [
      {
        name: "implementation",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
] as const;
